language: node_js

node_js:
  - 0.10

sudo: false

addons:
  sauce_connect: true

env:
  global:
    - secure: ZeXQYQkUTSbJnYge4Hd8My9m/mTpB4gpNJLaRYr9IIlMXC3ODBbTGkqbh9SpF+cI8p1IYHaQCJxVu+eyzhwayn1KON2Dp5hcS3HOHTHcPX0WmTEofJ5pGAd9DI4xcbxcTLU5cSAYTuhsd1tehHhawyGLVJ/3odAgHieAbsU7JqM=
    - secure: IxrAVc/QdvyHx/xAjQ5wIJQGsbtu6VoH/tVZRAWjh7HXebmafszeCtWlxZQ+ezJfTqZORxnFBlQe6JSQueoTkeaL+V5hWcWPfFs1peXzNlRu+1d+t9t3q+8wjvuxsWM770iqowj7lt2LFUaTuiH4QJYU/snnlPYpIoz+bpJaq5k=

  matrix:
    - BROWSER_NAME='firefox' BROWSER_VERSION='31' PLATFORM='Windows XP'
    - BROWSER_NAME='firefox' BROWSER_VERSION='32' PLATFORM='Windows XP'
    - BROWSER_NAME='firefox' BROWSER_VERSION='33' PLATFORM='Windows XP'
    - BROWSER_NAME='firefox' BROWSER_VERSION='33' PLATFORM='OS X 10.9'
    - BROWSER_NAME='chrome' BROWSER_VERSION='35' PLATFORM='Windows XP'
    - BROWSER_NAME='chrome' BROWSER_VERSION='36' PLATFORM='Windows XP'
    - BROWSER_NAME='chrome' BROWSER_VERSION='37' PLATFORM='Windows XP'
    - BROWSER_NAME='chrome' BROWSER_VERSION='38' PLATFORM='Windows XP'
    - BROWSER_NAME='chrome' BROWSER_VERSION='38' PLATFORM='OS X 10.8'

before_script:
  - npm install -g bower
  - bower install

script: npm test
