language: node_js

node_js:
  - 0.10

sudo: false

cache:
  directories:
    - node_modules
    - bower_components

addons:
  sauce_connect:
    username: scribe-ci
    access_key: 4be9eeed-61de-4948-b18d-f7f655e9e4b0

env:
  matrix:
    - BROWSER_NAME='firefox' BROWSER_VERSION='40' PLATFORM='Windows 7'
    - BROWSER_NAME='firefox' BROWSER_VERSION='40' PLATFORM='OSX 10.9'
    - BROWSER_NAME='chrome' BROWSER_VERSION='43' PLATFORM='Windows 7'
    - BROWSER_NAME='chrome' BROWSER_VERSION='43' PLATFORM='OSX 10.9'
    - BROWSER_NAME='chrome' BROWSER_VERSION='44' PLATFORM='Windows 7'
    - BROWSER_NAME='chrome' BROWSER_VERSION='44' PLATFORM='OSX 10.9'

before_script:
  - npm install -g bower
  - bower install

script: npm test
